imports:
    - { resource: parameters.default.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:
        fallback: en
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            ~
    csrf_protection: ~
    validation:
        enable_annotations: true
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  en
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id:  ~
        cookie_httponly: true
        #cookie_secure: true
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
