parameters:
    locale:            en

    database_host:     127.0.0.1
    database_port:     ~
    database_password: ~

    mailer_transport: null
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null

    secret:            ThisTokenIsNotSoSecretChangeIt
