security:
    session_fixation_strategy: migrate
    providers:
        in_memory:
            memory: ~

    firewalls:
        dev:
            pattern: ^/(_(error|profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~
